- name: Install epel-release
  yum:
    name: epel-release
    state: "{{ desired_state_basic }}"

- name: Install core packages
  yum:
    name: "{{ main_packages }}"
    state: "{{ desired_state_basic }}"
  with_items: "{{ main_packages }}"
